import torch
import torch.nn as nn

class FeaturePreprocessingPipeline:
    """
    FEATURE PREPROCESSING PIPELINE DOCUMENTATION & PREPARATION:
    ---------------------------------------------------------
    The raw Structured Transaction output from NER contains string entities:
    - Merchant: String (e.g. "Amazon", "Swiggy", "Starbucks")
    - Bank: String (e.g. "HDFC", "SBI", "ICICI")
    - Mode: String (e.g. "UPI", "Debit Card", "NetBanking")
    - Description / Transaction Type: String (e.g. "Debit", "Spent", "Payment")
    - Amount: Numeric / String (e.g. 500.0)

    NUMERICAL FEATURE CONVERSION STEPS:
    1. Categorical Encoding:
       - Merchant, Bank, Mode, and Description must be encoded using Categorical One-Hot Encoding, 
         Target Encoding, or Pre-trained Word Embeddings (e.g. FastText / TF-IDF vectors).
    2. Numerical Normalization:
       - Amount must be log-transformed or normalized using StandardScaler: x_norm = (x - mu) / sigma.
    3. Concatenation:
       - Combine vector components into a dense float vector of dimension `input_features`.

    TODO: Implement automated TF-IDF / One-Hot vectorizer pipeline in feature_vectorizer.py prior to model training.
    """
    def __init__(self):
        # TODO: Initialize OneHotEncoder / TF-IDF Vectorizers for Merchant, Bank, Mode
        pass

    def transform(self, structured_transaction_dict: dict) -> torch.Tensor:
        # TODO: Convert structured string dictionary into normalized numerical PyTorch tensor
        # Placeholder returning zero vector of length input_features
        raise NotImplementedError("Feature preprocessing pipeline TODO: implement feature_vectorizer.py")


class ExpenseClassifier(nn.Module):
    """
    Independent lightweight MLP for Expense Category Classification.
    Input: Numerical Feature Vector generated by FeaturePreprocessingPipeline.
    Output: Category logits (Food, Shopping, Travel, Bills, Investment, Others).
    """
    def __init__(self, input_dim: int, hidden_dim: int, num_classes: int = 6, dropout_prob: float = 0.2):
        super(ExpenseClassifier, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout_prob),
            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x):
        return self.network(x)
